"""Change model

Revision ID: d4f0622267d8
Revises: db4f4c51b366
Create Date: 2024-05-17 12:24:22.563358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4f0622267d8'
down_revision: Union[str, None] = 'db4f4c51b366'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange_rates', sa.Column('datetime', sa.String(), nullable=True))
    op.add_column('exchange_rates', sa.Column('exchange_rate', sa.Float(), nullable=True))
    op.drop_column('exchange_rates', 'date')
    op.drop_column('exchange_rates', 'rate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange_rates', sa.Column('rate', sa.FLOAT(), nullable=True))
    op.add_column('exchange_rates', sa.Column('date', sa.VARCHAR(), nullable=True))
    op.drop_column('exchange_rates', 'exchange_rate')
    op.drop_column('exchange_rates', 'datetime')
    # ### end Alembic commands ###
